### PR TITLE
Metrics - return cached value if unique sessions count crashes

### LINKED ISSUE #521: Exometer reporter crashes when calculating uniqueSessionCount
Crash log:
```
** Last message in was {report,{key,exometer_report_graphite,[global,uniqueSessionCount],default,false,[]},5000}
** When Server state == {st,[],[]}
** Reason for termination ==
**
{{aborted,{badarg,[session,{{1442,941593,580189},<0.23291.6>}]}},[{mnesia,abort,1,[{file,"mnesia.erl"},{line,310}]},{ejabberd_sm_mnesia,compute_unique,2,[{file,"src/ejabberd_sm_mnesia.erl"},{line,125}]},{exometer_function,call_once,5,[{file,"src/exometer_function.erl"},{line,326}]},{exometer_function,get_value,4,[{file,"src/exometer_function.erl"},{line,230}]},{exometer,get_value,2,[{file,"src/exometer.erl"},{line,304}]},{exometer_report,get_values,2,[{file,"src/exometer_report.erl"},{line,1297}]},{exometer_report,do_report,2,[{file,"src/exometer_report.erl"},{line,1099}]},{exometer_report,handle_info,2,[{file,"src/exometer_report.erl"},{line,1021}]}]}
2015-09-22 19:09:58 =CRASH REPORT====
  crasher:
      initial call: exometer_report:init/1
      pid: <0.87.0>
      registered_name: exometer_report
      exception exit: {{aborted,{badarg,[session,{{1442,941593,580189},<0.23291.6>}]}},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,804}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
      ancestors: [exometer_sup,<0.83.0>]
```
It seems that there is race condition when calling mnesia:dirty_next, the key can be already removed and it mensia throws exception.

### PR DESCRIPTION
**Pull request by michalwski**
Fixes #521

### CODE REVIEW

**Comment by michalwski** [comment]
Trigger travis for latest commit (for some reason the build didn't start).

File: apps/ejabberd/test/ejabberd_sm_SUITE.erl [hunk 1]
```diff
@@ -188,9 +195,22 @@ unique_count(C) ->
     UsersWithManyResources = generate_many_random_res(5, 3, [<<"localhost">>, <<"otherhost">>]),
     [given_session_opened(Sid, USR) || {Sid, USR} <- UsersWithManyResources],
     USDict = get_unique_us_dict(UsersWithManyResources),
-    UniqueCount = ?B(C):unique_count(),
+    UniqueCount = ejabberd_sm:get_unique_sessions_number(),
     UniqueCount = dict:size(USDict).
 
+
+unique_count_while_removing_entries(C) ->
+    unique_count(C),
```
Comment (fenek) [inline apps/ejabberd/test/ejabberd_sm_SUITE.erl]: Why is it called here?
