### PR TITLE
Fix #904 - broken MUC light config update due to invalid sanitisation

### LINKED ISSUE #904: Broken configuration update in MUC Light
MongooseIM version: master (557ddd92bb30ff5d12419db71f77b1a0399bb38d)
Installed from: source
Erlang/OTP version: 17.5

An issue was found by @andresinaka where MUC Light room config is not updated properly (fields get duplicated).

```
<iq xmlns='jabber:client' from='3d84688e-d151-4d84-ba76-4dd20782e1c2@muclight.erlang-solutions.com' to='ramabit@erlang-solutions.com/Andress-MacBook-Pro' id='config0' type='result'>
  <query xmlns='urn:xmpp:muclight:0#configuration'>
    <version>1468-525168-859460</version>
    <roomname>test</roomname>
    <subject/>
  </query>
</iq>

<iq id='conf2' to='3d84688e-d151-4d84-ba76-4dd20782e1c2@muclight.erlang-solutions.com' type='set'>
   <query xmlns='urn:xmpp:muclight:0#configuration'>
      <subject>racataca</subject>
      <roomname>2222222</roomname>
      <subject>racataca1</subject>
      <subject>racataca1</subject>
   </query>
</iq>

<message xmlns='jabber:client' from='3d84688e-d151-4d84-ba76-4dd20782e1c2@muclight.erlang-solutions.com' to='ramabit@erlang-solutions.com' id='conf2' type='groupchat'>
  <x xmlns='urn:xmpp:muclight:0#configuration'>
    <prev-version>1468-525168-859460</prev-version>
    <version>1468-867540-791625</version>
    <subject>racataca1</subject>
    <subject>racataca1</subject>
    <roomname>2222222</roomname>
    <subject>racataca</subject>
  </x>
  <body/>
</message>

<iq xmlns='jabber:client' from='3d84688e-d151-4d84-ba76-4dd20782e1c2@muclight.erlang-solutions.com' to='ramabit@erlang-solutions.com/Andress-MacBook-Pro' id='conf2' type='result'/>

<iq id='config0' to='3d84688e-d151-4d84-ba76-4dd20782e1c2@muclight.erlang-solutions.com' type='get'>
   <query xmlns='urn:xmpp:muclight:0#configuration'/>
</iq>

<iq xmlns='jabber:client' from='3d84688e-d151-4d84-ba76-4dd20782e1c2@muclight.erlang-solutions.com' to='ramabit@erlang-solutions.com/Andress-MacBook-Pro' id='config0' type='result'>
  <query xmlns='urn:xmpp:muclight:0#configuration'>
    <version>1468-867540-791625</version>
    <roomname>test</roomname>
    <subject>racataca</subject>
    <roomname>2222222</roomname>
    <subject/>
  </query>
</iq>
```

Original suspicion is that duplicated fields or repetitive field changes break config eventually.

### PR DESCRIPTION
**Pull request by fenek**
This PR addresses #904 

* Config changes in MUC Light are now properly applied.
* Separation of responsibilities: main MUC Light code ensures config fields uniqueness after parsing the requests, the backend ensures the order of fields.

### CODE REVIEW

File: test/ejabberd_tests/tests/muc_light_SUITE.erl [hunk 1]
```diff
@@ -38,6 +38,7 @@
          destroy_room_get_disco_items_empty/1,
          destroy_room_get_disco_items_one_left/1,
          set_config/1,
+         assorted_config_doesnt_lead_to_duplication/1,
```
Comment (michalwski) [inline test/ejabberd_tests/tests/muc_light_SUITE.erl]: I like the test case name :D 👍
